# Generated by Django 5.2.6 on 2025-09-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
