name: Deploy Assessment-1

on:
  push:
    branches:
      - assessment-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to AWS S3
        run: |
          aws s3 sync dist/ s3://$AWS_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
