name: Deploy Tareas

on:
  push:
    branches:
      - hw-04  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Compilar el proyecto (Vite build)
      - name: Build project
        run: npm run build

      # 5. Subir a S3
      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ secrets.S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 6. Invalidar la caché en CloudFront
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
